# **Numpy Introduction:**
Numpy Website: [Website Link](https//numpy.org/)\
Numpy Documentation: [Documentation Link](https://numpy.org/doc/stable/)\
Numpy Beginner Guide: [Guide Link](https://numpy.org/doc/stable/user/absolute_beginners.html)\

> NumPy is a powerful numerical computing library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. 

- **NumPy Basics:**
- NumPy stands for `Numerical Python`, and it is an essential library for `numerical computing` in Python.
- It introduces a new data structure called "`NumPy arrays`" that are more efficient for numerical operations than `Python lists`.

### **Key Features:** 

1. **Multidimensional Arrays:**
- NumPy provides support for multidimensional arrays, which can be 1-dimensional, 2-dimensional, or even more.
2. **Element-Wise Operations:**
- NumPy allows for element-wise operations, making it efficient for mathematical and logical operations on arrays.
3. **Broadcasting:** 
- NumPy automatically handles operations between arrays of different shapes and sizes through a mechanism called broadcasting.

### **Functionalities:**

1. **Array Creation and Manipulation:**
- NumPy provides functions to create arrays from Python lists or other existing arrays.
- Array manipulation functions allow reshaping, stacking, and splitting arrays.
2. **Mathematical Operations:**
- NumPy provides a wide range of mathematical functions for operations like addition, subtraction, multiplication, and more.
- These operations can be performed element-wise or on entire arrays.
3. **Linear Algebra:**
- NumPy includes a comprehensive set of functions for linear algebra operations, such as matrix multiplication, eigenvalue decomposition, and solving linear systems.
4. **Random Number Generation:**
- NumPy has a robust random module for generating random numbers, distributions, and permutations.
5. **Statistical Operations:**
- NumPy provides functions for various statistical operations, including mean, median, standard deviation, and correlation.
6. **Indexing and Slicing:**
- NumPy supports advanced indexing techniques, including boolean indexing and fancy indexing, making it flexible for selecting and manipulating data.
### **Applications:**

1. **Scientific Computing:**
- NumPy is widely used in scientific and engineering applications for numerical simulations and data analysis.
2. **Machine Learning:** 
- Many machine learning frameworks, such as TensorFlow and scikit-learn, rely on NumPy for efficient numerical computations.
3. **Data Analysis:**
- NumPy is a fundamental tool in data analysis and manipulation, often used in conjunction with pandas, another popular data manipulation library in Python.
4. **Signal Processing:**
- It's used for tasks like image processing and signal processing due to its efficient array operations.
5. **Community and Ecosystem:**
- NumPy has a large and active community, contributing to its continuous improvement and development.
- It is a fundamental building block for many other scientific computing libraries in Python.

### **What is an array?**

- An array is a data structure in programming that stores a collection of elements, typically of the same data type, in a contiguous block of memory. It is a fundamental concept in many programming languages, including Python, and is used extensively in scientific computing, data analysis, and machine learning. 

- In Python, the NumPy library provides support for arrays and enables efficient numerical operations on them. NumPy arrays are more efficient than Python lists for numerical operations because they are implemented in C and allow for vectorized operations.
- `We convert images, audios etc into numbers (arrays) and apply algorithms on it`.

### **Install Numpy:**

In [1]:
# Insatll numpy:
# pip3 install numpy
# conda install numpy

### **Import Numpy:**

In [2]:
# Import numpy:
import numpy as np

### **1-D Array**:
- These are the `simplest form of arrays` and are often used to store and manipulate data like lists. 
- They are particularly useful when dealing with `sequential data` or when performing `mathematical operations` that can be `vectorized`.

In [3]:
a = np.arange(6)
# 1-D array 

print(a)
a.shape
# Shape of array

[0 1 2 3 4 5]


(6,)

- `6 elements` from 0 to 5

### **2-D Arrays:** 
- These are often used to represent `matrix-like data structures`, like images (grayscale images), spreadsheets, or adjacency matrices in graph theory. 
- In `machine learning`, 2D arrays are often used to represent datasets where each `row` is a `sample` and each `column` is a `feature` of the sample.

In [4]:
a2 = a[np.newaxis,  :]
# Add a new axis to an array at the specified index (axis)

print(a2)

# shape of array
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

#### **Key Points**:
---
- `[[]]` shows 2-D array 
- 1st axis = 1 row 
- 2nd axis = 6 columns
- `1 row and 6 columns` 

In [5]:
a2 = a[ : , np.newaxis]
# Add a new axis to an array at the specified index (axis)

print(a2)

# shape of array
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

- `1 column` & `6 rows`

### **3-D arrays:** 
- These are used when dealing with `volumes` or when each data point is represented as a `matrix` itself. 
- For example, in `computer vision`, `color images` are often represented as 3D arrays (height, width, color channels). 
- In `natural language processing`, a batch of sentences might be represented as a 3D array (batch size, sentence length, word vector size).

**In summary, the dimensionality of the array you use in data science largely depends on the nature of your data and the problem you're trying to solve.**

In [6]:
a3 = a2[np.newaxis, :]
# Add a new axis to an array at the specified index (axis)

print(a3)
a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

#### Key Points:
---
- `[[[]]]` shows 3-D array 
- `1 row` and `1 column` and `6 elements` in each row and column 

---

# **Creating Arrays with Numpy:**

#### **1D & 2D Arrays**:

In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
# a is a 1-D array

b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])
# b is a 2-D array

print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4 5 6 7]
(7,)
[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]
(2, 7)


In [8]:
# type of array(a):
type(a) 

numpy.ndarray

- `ndarray` = n dimensional array

In [9]:
# data type of array(a) elements:
a.dtype 

dtype('int32')

In [10]:
# type of array(b):
type(b)

numpy.ndarray

- `ndarray` = n dimensional array

In [11]:
# data type of array(b) elements:
b.dtype

dtype('int32')

# **Initialize Arrays:**

#### **1. `zeros` function**:
- A `zeros array can` also be referred to as a ~, especially when it's `two-dimensional`.
- In NumPy, a zeros array is an array that is filled with the `value 0`. You can create a zeros array of any shape using the `numpy.zeros()` function. 
> It's **important to note** that while a zeros matrix is a type of zeros array, `not all zeros arrays are zeros matrices`. 
> This is because arrays in NumPy can have any number of dimensions, while matrices are typically two-dimensional. For example, `numpy.zeros((3, 3, 3))` creates a 3D zeros array, which wouldn't typically be referred to as a matrix.

**Uses of zeros array:**

`1. Initializing arrays:` 
- Zeros arrays are often used to initialize an array before filling it with actual values. This is especially common in machine learning and computer graphics.

`2. Resetting or clearing data: `
- If you have an existing array and you want to reset all its values to zero, you can simply replace it with a zeros array of the same shape.

`3. Padding data:` 
- In data processing, it's common to need to pad an array with zeros to make it fit a certain shape. For example, in image processing, you might need to pad an image with zeros to make it square.

`4. Creating masks for image processing:` 
- In image processing, a zeros array of the same size as the image can be used to create a mask that blocks all pixels.

`5. Performing operations over an entire array:` 
- If you need to subtract an array from itself, or multiply it by zero, you can use a zeros array to do this efficiently.

`6. Creating a placeholder for data:` 
- If you're loading data in chunks, you can create a zeros array of the full size you expect, and then fill in each chunk as you load it. This can be more efficient than concatenating arrays.

In [12]:
# zeros array:
zeros = np.zeros((3, 5)) # (rows, columns)
zeros  # print zeros array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# data type of array(zeros) elements:
zeros.dtype

dtype('float64')

#### **2. `ones` function**:
- A ones array can also be referred to as a ones matrix, especially when it's two-dimensional.
- In NumPy, a ones array is an array that is filled with the `value 1`. 
- You can create a ones array of any shape using the `numpy.ones()` function. 

> Just like with zeros arrays, while a ones matrix is a type of ones array, not all ones arrays are ones matrices. This is because arrays in NumPy can have any number of dimensions, while matrices are typically two-dimensional.

**Uses of ones array:** 

`1. Initializing weights in machine learning algorithms: `
- In some machine learning algorithms, it's common to initialize the weights to 1 before training starts.

`2. Creating masks for image processing: `
- In image processing, a ones array of the same size as the image can be used to create a mask that allows all pixels to pass through.

`3. Performing operations over an entire array:` 
- If you need to add, multiply, or perform some other operation on all elements of an array, you can use a ones array to do this efficiently.

`4. Creating an array with a specific value:` 
- If you need an array filled with a specific value, you can create a ones array and then multiply it by that value. 
- For example, `numpy.ones((3, 3)) * 5` creates a 3x3 array filled with the number 5.

In [14]:
# ones array:
ones = np.ones((3, 5))
ones  # print ones array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# data type of array(ones) elements:
ones.dtype

dtype('float64')

#### **3. `full` function**:
- A full array can also be referred to as a full matrix, especially when it's two-dimensional.
- In NumPy, a full array is an array that is filled with a `specified value`. You can create a full array of any shape using the `numpy.full()` function. 
- For example, `numpy.full((3, 3), 7)` will create a 3x3 full matrix (a 2D array filled with the number 7).

> Just like with zeros and ones arrays, while a full matrix is a type of full array, not all full arrays are full matrices. This is because arrays in NumPy can have any number of dimensions, while matrices are typically two-dimensional.

A full array is useful when you need an array of a certain size that is filled with a specific value. This can be more efficient than creating a zeros or ones array and then multiplying or adding to get the desired value.

**Uses of full array:**

`1. Initializing arrays with a specific value:` 
- Full arrays are often used to initialize an array with a specific value before filling it with actual values. This is common in various fields including machine learning and data analysis.

`2. Creating constant arrays for calculations:` 
- If you need an array of a certain size that is filled with a specific constant value for calculations, you can use a full array. For example, you might need an array filled with the value of pi or e for mathematical computations.

`3. Creating masks for data processing:` 
- In data processing, a full array of the same size as your data can be used to create a mask that allows or blocks certain values.

`4. Performing operations over an entire array:` 
- If you need to add, subtract, multiply, or divide an entire array by a specific value, you can create a full array of that value and then perform the operation.

`5. Filling missing data:` 
- In data analysis, you might have missing data that you want to fill with a specific value. You can create a full array of that value and then use it to fill the missing data.

`6. Creating test data:` When writing tests for your code, you might need an array of a certain size that is filled with a known value. A full array is a quick and easy way to create such test data.

In [16]:
# full array with a specific/desired value:
full = np.full((3, 5), 7.5)
# (rows, columns), value
# 7.5 is the desired value

full # print full array

array([[7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5]])

In [17]:
# data type of array(full) elements:
full.dtype

dtype('float64')

#### **4. `identity` function:**
- An identity array is the same as an identity matrix.
- In the context of NumPy, the term "identity array" is often used, but mathematically, it's known as an "identity matrix".
- An identity matrix is a square matrix (same number of rows as columns) with ones on the main diagonal and zeros everywhere else. 
- It's called an "identity" matrix because, when it's multiplied by any other matrix, it doesn't change the other matrix, much like how multiplying a number by one doesn't change the number.
> In NumPy, you can create an identity matrix using the `numpy.eye()` or `numpy.identity()` function. For example, `numpy.eye(3)` or `numpy.identity(3)` will create a 3x3 identity matrix.

**Uses of Identity Array:**

`1. Matrix multiplication:` 
- The identity matrix is often used in matrix multiplication. When you multiply any matrix by an identity matrix, the original matrix is unchanged. This is similar to multiplying any number by 1; the original number remains the same.

`2. Solving systems of linear equations:` 
- Identity matrices are used in methods for solving systems of linear equations, such as Gaussian elimination or matrix inversion.

`3. Initializing matrices in machine learning algorithms:` 
- In some machine learning algorithms, it's common to initialize the weights to an identity matrix before training starts.

`4. Performing transformations in computer graphics:` 
- In computer graphics, the identity matrix is used as the basis for transformation matrices that move, rotate, and scale shapes.

`5. Testing matrix multiplication functions:` 
- When writing or testing functions that perform matrix multiplication, it's useful to have an identity matrix to check that the function is working correctly. 
- If you multiply a matrix by an identity matrix using the function, and the original matrix is unchanged, then the function is likely working correctly.

In [18]:
# creating an identity matrix:
identity = np.eye(5) 
identity  # print identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# data type of array(identity) elements:
identity.dtype

dtype('float64')

# **Array Attributes:**
> Array attributes in NumPy are properties of the array that provide information about its structure and data. 

**Here are some of the main attributes:**

1. **ndarray.ndim**: This attribute returns the number of array dimensions. For example, for a 2D array, `ndim` would be 2.

2. **ndarray.shape**: This attribute returns a tuple representing the dimensions (shape) of the array. For example, for a 2D array with 2 rows and 3 columns, `shape` would be (2, 3).

3. **ndarray.size**: This attribute returns the total number of elements in the array.

4. **ndarray.dtype**: This attribute returns the data type of the array elements.

5. **ndarray.itemsize**: This attribute returns the size (in bytes) of each element in the array.

6. **ndarray.data**: This attribute is a buffer containing the actual elements of the array.

7. **ndarray.nbytes**: This attribute returns the total bytes consumed by the elements of the array.

8. **ndarray.strides**: This attribute returns a tuple of bytes to step in each dimension when traversing an array.

These attributes provide useful information when you're manipulating and analyzing data with NumPy.

In [21]:
a.shape # shape of array

(7,)

In [20]:
len(b) # give us the length of array

2

In [22]:
b.size # gives us the total numbers of elements in array

14

In [23]:
b.ndim # give us the dimension of array

2

# **Basic Operations:**
NumPy arrays support a variety of operations. Here are some basic ones:

1. **Arithmetic Operations**: You can perform element-wise arithmetic operations (`addition, subtraction, multiplication, division`) on arrays of the same size. 

2. **Scalar Operations**: You can perform arithmetic operations with a scalar (`a single number`) and an array. 

3. **Comparison Operations**: You can perform element-wise comparison operations on arrays. 

4. **Matrix Operations**: You can perform matrix operations like `dot product`.

5. **Aggregation Functions**: NumPy provides functions to compute statistics of data in arrays.

6. **Reshaping**: You can `change` the `number of rows and columns` in an array without changing the data.

7. **Indexing and Slicing**: You can access elements in an `array` using `indices`, and you can access `subarrays` using `slices`.

These are just a few examples of the operations you can perform with NumPy arrays. There are many more functions and methods available in the NumPy library.

#### **1. Arithmetic Operations:**

In [38]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # array([5, 7, 9])
print(a - b)  # array([-3, -3, -3])
print(a * b)  # array([ 4, 10, 18])
print(a / b)  # array([0.25, 0.4 , 0.5 ])
print(a**2)   # array([1 4 9])

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


#### **2. Scalar Operations:**

In [32]:
a = np.array([1, 2, 3])

print(a + 1)  # array([2, 3, 4])
print(a * 2)  # array([2, 4, 6])

[2 3 4]
[2 4 6]


#### **3. Comparison  Operations:**

In [33]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])

print(a == b)  # array([ True,  True, False])
print(a < b)   # array([False, False,  True])

[ True  True False]
[False False  True]


#### **4. Matrix Operations:**

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))  # array([[19, 22], [43, 50]])

[[19 22]
 [43 50]]


#### **5. Aggression Functions:**

In [35]:
a = np.array([1, 2, 3, 4])

print(np.sum(a))  # 10
print(np.mean(a)) # 2.5
print(np.min(a))  # 1
print(np.max(a))  # 4

10
2.5
1
4


#### **6. Reshaping:**

In [36]:
a = np.array([1, 2, 3, 4])

b = a.reshape(2, 2)
print(b)  # array([[1, 2], [3, 4]])

[[1 2]
 [3 4]]


#### **7. Indexing & Slicing:**

In [37]:
a = np.array([1, 2, 3, 4])

print(a[0])    # 1
print(a[1:3])  # array([2, 3])

1
[2 3]


---

#### Other Rough Practice:

In [24]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [26]:
#1 Subtraction:
g = a - b 
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [27]:
#2 Addition:
h = a + b
h 

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [28]:
#2.1 Another method of Addition:
h1 = np.add(a, b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [29]:
#3 Multiplication:
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [30]:
#4 Division:
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [92]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
#5 Square of each element:
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])

---

# Information about the author:

- **Author**: Muhammad Fareed Khan
- **Code Submission Date**: 14-12-2023
- **Author's Contact Info**:
  
    - Email: [Email](mailto:contact@mfareedkhan.com)
    - Github: [Github](https://github.com/fareedkhands)
    - Kaggle: [Kaggle](https://www.kaggle.com/muhammadfareedkhan)
    - LinkedIn: [LinkedIn](https://www.linkedin.com/in/fareed-khan-385b79150/)
    - Twitter: [Twitter](https://twitter.com/fareedkhanmeyo)
