# **Numpy (Part-2)**

- Numpy Website: [Website Link](https//numpy.org/)
- Numpy Documentation: [Documentation Link](https://numpy.org/doc/stable/)
> Numpy Beginner Guide: [Guide Link](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [1]:
import numpy as np

# **Initialize Arrays:**

#### **5. `empty` function:**
> An empty array in NumPy is an array that is allocated but not populated with any data. When you create an empty array using `numpy.empty()`, it is filled with whatever values were already in memory at that location. 

`a = np.empty(3)`- empty aray with 3 elements

- The `output` of this code will be an array with 3 elements, but the values of those elements are `unpredictable`.

**Use of empty array?**
- The main use of `numpy.empty()` is to allocate large arrays when you know that you're going to overwrite all of the elements. 
- Because `numpy.empty()` does not initialize the array elements to any particular values like `numpy.zeros()` or `numpy.ones()` do, it can be slightly faster if you're creating a large array.

> However, you should be careful when using `numpy.empty()`, because it can sometimes lead to confusing results if you assume that the array will be initialized to zeros or some other value.

In [2]:
empty_1 = np.empty((2))     # Create an uninitialized array with 2 elements
print(empty_1)              # Print the array

print("------------")       # Print a separator to make the output more readable

empty_2 = np.empty((2, 3))  # Create an uninitialized array with 2 rows and 3 columns
print(empty_2)              # Print the array

print("------------")       # Print a separator to make the output more readable

print(empty_2[0])           # Print the first element of the array
print("------------")       # Print a separator 
print(empty_2[1])           # Print the second element of the array
# in the output values the negative power of e shows that the values are very small and close to zero but not zero 
# but positive   

[ 4.52231634e+150 -6.24773225e+178]
------------
[[4.45061032e-308 9.34604358e-307 1.37959129e-306]
 [1.33511969e-306 1.24611266e-306 2.11382017e-307]]
------------
[4.45061032e-308 9.34604358e-307 1.37959129e-306]
------------
[1.33511969e-306 1.24611266e-306 2.11382017e-307]


### **Key Points:**
- The first element `([0])` of the array is not initialized, so it can be anything
- The second element `([1])` of the array is not initialized, so it can be anything
- The `np.empty()` function in NumPy creates an array without initializing its elements to any particular values. 
- It simply allocates the memory for the array. 
- The values that you see in the array are whatever values were already present in the memory.
> When you see `very small` or very `large numbers` in scientific notation (like `1.47039e+224` or `2.47033e-323`), these are just the values that happened to be in the memory locations that were allocated for the array. They don't have any particular meaning, and you can't make any assumptions about them.
- If you're going to use an array created with `np.empty()`, you should make sure to fill it with your own values before you use it. Otherwise, you might get unpredictable results from your code.

#### **6. `arange` function:**
- The `np.arange()` function in NumPy is used to generate sequences of numbers within a defined interval. 
- It's similar to the built-in Python function `range()`, but it returns a NumPy array.

> **Usage**: The `np.arange()` function is useful when you need to create an array with a sequence of numbers, especially for use as an index array.

In [3]:
#1 Create an array with values from 0 to 22
x = np.arange(23)  
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


- the first element is `0` and the last element is `22`
- the elements are separated by `1` & are `integers`
- the array is `one dimensional`
- the array is a `vector`

- You can also specify a `start value`, an `end value`, and a `step value`:

In [4]:
#2 Create an array with values from 0 to 23, stepping by 2
# Even numbers:
y = np.arange(0, 23, 2)
print(y)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


- `Even numbers` from 0 to 22
- `stepping by 2` means that the array will start from 0 and end at 22 but the values will be `incremented by 2`
- Note that the end value is exclusive, so `np.arange(0, 23, 2)` generates values up to but not including 23.

In [5]:
#3 Create an array with values from 0 to 23, stepping by 2
# Odd numbers:
z = np.arange(1, 23, 2)
print(z)

[ 1  3  5  7  9 11 13 15 17 19 21]


- `Odd numbers` from 1 to 22

In [6]:
# Create an array with specific differnce b/w numbers
diff = np.arange(0, 23, 0.515) # 0.515 is the difference between numbers
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

#### **6. `linspace` function:**
>The `np.linspace()` function in NumPy is used to generate a sequence of evenly spaced values over a specified range. 
> It's particularly useful when you need a specific number of points within a defined interval.


**Useful**: This can be useful in a variety of contexts, such as: 
- generating a sequence of time points for a simulation
- creating a grid of values for a numerical method
- or generating input values for a function plot.

In [7]:
lin = np.linspace(0, 10, num=100000000) # num is the number of elements in the array
print(lin)

[0.00000000e+00 1.00000001e-07 2.00000002e-07 ... 9.99999980e+00
 9.99999990e+00 1.00000000e+01]


- `np.linspace(0, 10, num=100000000)` generates `100000000` evenly spaced values between `0` and `10` inclusive.
- `(0, 10, num=15)` means 15 linearly spaced numbers b/w 0 and 10 including 0 and 10
- `linear` means difference b/w numbers is same

#### **Data Type of Array:**

In [8]:
#1 to check the data type of the array:
lin.dtype 

dtype('float64')

- `dtype('float64')` means that the array is of type float and has 64 bits

In [9]:
# define the dtype of array:
x = np.arange(0 ,22.6, 1.5, dtype=np.float64)
print(x)

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.  16.5 18.  19.5
 21.  22.5]


---

#### **What is the difference between below all:** 
#### `int8, int16, int32, int64, int128, in256` and `float 16, float32, float64, float80, float96, float128, float256`
  
**int numbers:**
- In NumPy, `int8`, `int16`, `int32`, `int64` are integer types that represent numbers with `no decimal point`. 
- The number following "int" indicates the `number of bits` that the type uses. 
- `More bits` allow for `larger numbers` but also use `more memory`. 
- For example: 
  - `int8` can represent integers from -128 to 127, while `int64` can represent much larger numbers.

**float numbers:**
- Similarly, `float16`, `float32`, `float64`, `float80`, `float96`, `float128` are floating point types that represent real numbers (numbers `with a decimal point`). 
- Again, the number following "float" indicates the number of bits that the type uses. 
- More bits allow for greater precision and larger numbers, but also use more memory.

Here's a brief overview:

- `int8`: Integer (-128 to 127)
- `int16`: Integer (-32768 to 32767)
- `int32`: Integer (-2147483648 to 2147483647)
- `int64`: Integer (-9223372036854775808 to 9223372036854775807)

- `float16`: Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
- `float32`: Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
- `float64`: Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
- `float96`: Extended precision float: sign bit, 15 bits exponent, 64 bits mantissa (not available on all platforms)
- `float128`: Quadruple precision float: sign bit, 15 bits exponent, 112 bits mantissa (not available on all platforms)

> Note: The floating point types (`float16`, `float32`, `float64`, `float96`, `float128`) don't have a simple range like integer types do, because they represent real numbers, which can have a fractional part. Instead, they have a certain amount of precision, which is determined by the number of bits used for the mantissa (also known as the significand).

Here's a rough idea of the precision and range of these types:

- `float16`: Precision of about 3.3 decimal digits. Range from roughly 5.96e-08 to 65504.
- `float32`: Precision of about 7.2 decimal digits. Range from roughly 1.18e-38 to 3.4e38.
- `float64`: Precision of about 15.9 decimal digits. Range from roughly 2.23e-308 to 1.8e308.
- `float96` and `float128`: These types have even more precision and a larger range, but they're not available on all platforms.

> Note: There are no `int128`, `int256`, `float80`, `float256` types in NumPy. The maximum size for integer types in NumPy is `int64`, and for floating point types it's `float128` (but `float128` is not available on all platforms).


**Here's how you might create a `float32` and a `float64` in NumPy:**

In [10]:
import numpy as np

# Create a float32
a = np.float32(1.123456789)
print(a)  # Outputs: 1.1234568

# Create a float64
b = np.float64(1.123456789123456789)
print(b)  # Outputs: 1.1234567891234568


1.1234568
1.1234567891234568


- In this example, you can see that the `float32` only retains about 7 decimal digits of precision, while the `float64` retains more.

---

#### **7. Sorting/Arranging an Array:**

In [11]:
#1 defining an array with specific data type:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)

[2 1 5 3 7 4 6 8]


In [12]:
#2 sorting an array:
arr = np.sort(arr)
print(arr)

[1 2 3 4 5 6 7 8]


In addition to sort, which returns a sorted copy of an array, you can use:

- [argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#numpy.argsort), which is an indirect sort along a specified axis,

- [lexsort](https://numpy.org/doc/stable/reference/generated/numpy.lexsort.html#numpy.lexsort), which is an indirect stable sort on multiple keys,

- [searchsorted](https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html#numpy.searchsorted), which will find elements in a sorted array, and

- [partition](https://numpy.org/doc/stable/reference/generated/numpy.partition.html#numpy.partition), which is a partial sort.

To read more about sorting an array, see: [sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort).

#### **8. Concatenate function:**
- In the context of NumPy, `concatenate` is a function that joins two or more arrays along an existing axis. 

- `np.concatenate((a,b))` is joining the arrays `a` and `b` together. 
- If `a` and `b` are both **one-dimensional** arrays, the result will be a single one-dimensional array that contains the elements of `a` followed by the elements of `b`.
- For example: 
  - if `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])`, then `np.concatenate((a, b))` would result in `array([1, 2, 3, 4, 5, 6])`.
- If `a` and `b` are **multi-dimensional** arrays, they will be joined along the first axis (axis 0) by default, but you can specify a different axis by using the `axis` parameter. The arrays must have the same shape along all but the specified axis.

#### **Concatenate 1D Arrays:**

In [13]:
#1 defining an array with specific data type:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [14]:
#2 concatenate these arrays into one array:
c = np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


#### **Concatenate 2D Arrays:**

In [15]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array (2D)
y = np.array([[5, 6]])         # 1x2 array (2D)

In [16]:
len(x)
len(y)
print(len(x))
print(len(y))

2
1


##### **2D Array at axis=0:**

In [17]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

#### **Key Points:**
- to concatenate at `axis=0` the `number of columns should be same`
- axis=0 means `adding rows` (vertical)

##### **2D Array at axis=1:**

In [18]:
w = np.array([[5,1], [7,1]])   # 2x2 array (2D)
x = np.array([[1, 2], [3, 4]]) # 2x2 array (2D)

In [19]:
z1 = np.concatenate((w,x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

- to concatenate at `axis=1` the `number of rows should be same`
- axis=1 means `adding columns` (horizontal)

##### **3D Array:**
- We need `three 2D-Arrays` to create 3D-Array

In [20]:
# create a 3D array of size 3x2x4:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim


3

- `3x2x4` array means `3 arrays of size 2x4`
- We need three 2x4 (2D) arrays to create a 3D array of size 3x2x4 

In [21]:
len(array_example)
# len() function shows the number of elements in the first axis
# in this case the first axis is 3 so the len() function shows 3

3

In [22]:
array_example.size
# size() function shows the number of elements in the array

24

In [23]:
array_example.dtype
# dtype() function shows the data type of the elements in the array

dtype('int32')

In [24]:
array_example.shape
# shape() function shows the shape of the array in the form of (x,y,z)

(3, 2, 4)

In [25]:
# creata 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                          [[4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])
a1.shape


(3, 1, 4)

- 3x1x4 means `3 arrays of size 1x4`

In [26]:
# Reshape the array (a1) into a 2D array with 6 rows and 2 columns:
a2 = a1.reshape(6,2)
a2.shape

(6, 2)

In [27]:
a1 # let's see the original array 

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [28]:
a2 # let's see the reshaped array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [29]:
# Reshape the array (a2) into a 3D array with 3 rows, 2 columns, and 2 elements in each row and column:
a2.reshape(3,2,2) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

#### **How to convert a 1D array into a 2D array (how to add a new axis to an array):**

In [30]:
#1 create a 1D array:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape
print(a.shape)
print(a)
print(a.ndim)

(8,)
[1 2 3 4 5 6 7 8]
1


In [31]:
#2 convert that into 2D array:
b = a[np.newaxis, :]
print(b.shape)
print(b)
print(b.ndim)

(1, 8)
[[1 2 3 4 5 6 7 8]]
2


- `np.newaxis` is used to increase the dimension of the existing array by one more dimension
- `:` means all the elements in the array
- `: after the comma means` axis must be on rows and not on columns
- : after the comma means axis 1
- `[[]]` in output shows 2D array

In [32]:
c = a[: , np.newaxis]
# : before the comma means array whose axis is on the column
print(c.shape)
print(c)
print(c.ndim)

(8, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
2


#### **9. Indexing and Slicing:**
> Indexing and slicing in NumPy refer to accessing or extracting specific elements, rows, columns, or sections from an array.

**Indexing** is used to `access individual elements` in an array. 
- In a `one-dimensional` array, you can access elements just like you would in a standard Python list:

- a = np.array([1, 2, 3, 4, 5])\
  print(a[0])  # Outputs: 1\
  print(a[-1])  # Outputs: 5

In a `multi-dimensional` array, you can access elements by specifying the indices in each dimension, separated by commas:

- b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])\
  print(b[0, 0])  # Outputs: 1\
  print(b[1, 2])  # Outputs: 6

**Slicing** is used to `access a sequence of elements` in an array. The syntax is `start:stop:step`, where `start` is the index to start from, `stop` is the index to go up to (but not include), and `step` is the difference between each index in the slice:

- print(a[1:4])  # Outputs: [2 3 4]

In a `multi-dimensional` array, you can slice along each dimension:

- print(b[0:2, 1:3])  # Outputs: [[2 3]\
                     #           [5 6]]

- In this example, `b[0:2, 1:3]` gets the subarray consisting of the first two rows and the last two columns.

---
In NumPy, you can use a variety of boolean or conditional operators to perform element-wise comparisons and generate boolean arrays. Here are some of them:

- `>`: Greater than
- `<`: Less than
- `>=`: Greater than or equal to
- `<=`: Less than or equal to
- `==`: Equal to
- `!=`: Not equal to

You can also use the following functions for element-wise comparisons:

- `np.greater()`: Greater than
- `np.less()`: Less than
- `np.greater_equal()`: Greater than or equal to
- `np.less_equal()`: Less than or equal to
- `np.equal()`: Equal to
- `np.not_equal()`: Not equal to

And the logical operators are:

- `and`: Logical AND
- `or`: Logical OR
- `not`: Logical NOT
Additionally, you can use the following logical operations:

- `np.logical_and()`: Element-wise logical AND
- `np.logical_or()`: Element-wise logical OR
- `np.logical_not()`: Element-wise logical NOT
- `np.logical_xor()`: Element-wise logical XOR

#### **For 1D Array:**

In [33]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
print(a[1])
print(a[1:])
print(a[2:5])

2
[2 3 4 5 6 7 8]
[3 4 5]


We're using indexing and slicing to access elements of the array `a`.

- `a[1]` returns the element at index 1 of the array `a`. 
- In Python, indexing is zero-based, so `a[1]` returns the second element of the array. 
- `a[1:]` returns a slice of the array `a` starting from index 1 (the second element) to the end of the array. 
- `a[2:5]` returns a slice of the array `a` starting from index 2 (the third element) up to, but not including, index 5.

#### **Negative Indexing:**

In [35]:
print(a[-1])
print(a[-1:])
print(a[-2:-5])

8
[8]
[]


- `a[-1]` returns the last element of the array `a`, which is 8.
- `a[-1:]` returns a slice of the array `a` starting from the last element to the end of the array. Since the last element is the end of the array, this slice only contains the last element. 
- `a[-2:-5]` attempts to return a slice of the array `a` starting from the second last element up to, but not including, the fifth last element. However, because the start index is after the stop index in this case, this slice is empty. 

#### **For 2D Array:**

In [36]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [37]:
print(b[0])     # first row f b array
print(b[1])     # second row of b array
print(b[2])     # third row of b array
print(b[0, 1])  # first row and second element of b array
print(b[1:,1:]) # second and third row and second, third and fourth element of b array

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
2
[[ 6  7  8]
 [10 11 12]]


In [38]:
print(b[b < 5])   # print the elements of b which are less than 5
print(b[b > 5])   # print the elements of b which are greater than 5
print(b[b <= 10]) # print the elements of b which are less than or equal to 10
print(b[b >= 10]) # print the elements of b which are greater than or equal to 10
print(b[b == 10]) # print the elements of b which are equal to 10
print(b[b != 10]) # print the elements of b which are not equal to 10

[1 2 3 4]
[ 6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12]
[10]
[ 1  2  3  4  5  6  7  8  9 11 12]


In [39]:

print(b[b % 2 == 0]) # filter even numbers from b array, 0 is remainder when b is divided by 2

# b % 2 == 0 is a condition which is true for even numbers and false for odd numbers
# b[b % 2 == 0] is a filter which filters the elements of b array which satisfy the condition b % 2 == 0
# % is the remainder operator
print(b[b % 2 == 1]) # filter odd numbers from b array, 1 is remainder when b is divided by 2

[ 2  4  6  8 10 12]
[ 1  3  5  7  9 11]


#### Remainde Operator:

In [40]:
# filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

#### **Select elements that satisfy two conditions using the `&` and `|` operators:**

- ##### Using `&` (and) operator:

In [41]:
# Use two conditions and filter the arrays:
print(b[(b > 2) & (b < 11)])    # filter the elements of b which are greater than 2 and less than 11

# Use three conditions and filter the arrays:
print(b[(b > 2) & (b < 11) & (b % 2 == 0)]) # filter the elements of b which are greater than 2 and less than 11 and even

[ 3  4  5  6  7  8  9 10]
[ 4  6  8 10]


- ##### Using `|` (or) operator:

In [42]:
# Use two conditions and filter the arrays:
print(b[(b > 2) | (b < 11)]) # filter the elements of b which are greater than 2 or less than 11
# Use three conditions and filter the arrays:
print(b[(b > 2) | (b < 11) | (b % 2 == 0)]) # filter the elements of b which are greater than 2 or less than 11 or even

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### **How to create an array from existing data?**
- Create a New Array from from a section of your Array:

In [45]:
# Create an array from a section of an existing array:
a = np.arange(0,222,5)
print(a)
print(len(a))

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]
45


In [48]:
array_1 = a[40:45] # create an array from 40th to 45th element of a array
print(array_1)

[200 205 210 215 220]


- #### **`Stack` two existing arrays (Vertically / Horizontally):**
**What is difference between `Stack` & `Concatenate`?**

> `np.concatenate`, `np.vstack`, and `np.hstack` are all NumPy functions used to join two or more arrays. 
- The difference lies in how and where they join the arrays:

**`np.concatenate`:**
- Joins arrays along an existing axis. You need to specify the axis along which the arrays will be concatenated. 
- If no axis is specified, it defaults to `axis 0`.

- `c = np.concatenate((a, b))`  # Joins a and b along axis 0

**`np.vstack` (vertical stack):**
- Joins arrays along a new first axis (vertically). 
- It's equivalent to concatenation along the first axis after 1-D arrays of shape `(N,)` have been reshaped to `(1, N)`. 
- It's useful when you want to stack arrays in sequence vertically (row wise).

- `c = np.vstack((a, b))`  # Stacks a and b vertically

**`np.hstack` (horizontal stack):** 
- Joins arrays along a new last axis (horizontally). 
- It's equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis. 
- It's useful when you want to stack arrays in sequence horizontally (column wise).

- `c = np.hstack((a, b))`  # Stacks a and b horizontally

In [49]:
# Let's Create two arrays:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])
# length of these arrays must be same

In [55]:
# Let's stack these two arrays vertically:
c = np.vstack((a,b)) # vstack() function stacks the arrays vertically
print(c)

# concatenate these two arrays along the second axis (axis=1):
# d = np.concatenate((a,b), axis=1) # concatenate() function concatenates the arrays along the second axis (axis=1)
# print(d)
# AxisError: axis 1 is out of bounds for array of dimension 1

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [56]:
# Let's stack these two arrays horizontally:
c = np.hstack((a,b)) # hstack() function stacks the arrays horizontally
print(c)

# concatenate these two arrays along the first axis (axis=0):
e = np.concatenate((a,b), axis=0) # concatenate() function concatenates the arrays along the first axis (axis=0)
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### **Stacking 2D Arrays:**

In [61]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

# Let's stack these two arrays vertically:
a3 = np.vstack((a1,a2)) 
print(a3)

print('-------------------')

# Let's stack these two arrays horizontally:
a4 = np.hstack((a1,a2))
print(a4)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
-------------------
[[1 1 3 3]
 [2 2 4 4]]


#### **`hsplit` fucntion:**
> The `np.hsplit` function in NumPy is used to split an array into multiple sub-arrays horizontally (column-wise).

- The splitting is based on a specified number of equally sized sub-arrays, or at the specified indices along the second axis (which is the horizontal axis, hence the name `hsplit`).

- We use `np.hsplit` when we need to split our data into multiple subsets along the horizontal axis. This can be useful in a variety of data manipulation tasks.

In [66]:
x = np.arange(1, 25)
print(x)

print('-------------------')

print(x.reshape(2, 12))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
-------------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [71]:
# split the array into 3 equal-sized sub-arrays:
print(np.split(x, 3))

print('-------------------')

# split the array after the third and fourth column:
print(np.split(x, (3, 4)))

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16]), array([17, 18, 19, 20, 21, 22, 23, 24])]
-------------------
[array([1, 2, 3]), array([4]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])]


[Learn more about stacking and splitting arrays here.](https://numpy.org/doc/stable/user/quickstart.html#quickstart-stacking-arrays)

[Basic Array Operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)\
[Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)\
[More useful array operations](https://numpy.org/doc/stable/user/absolute_beginners.html#more-useful-array-operations)

---

# Information about the author:

- **Author**: Muhammad Fareed Khan
- **Code Submission Date**: 16-12-2023
- **Author's Contact Info**:
  
    - Email: [Email](mailto:contact@mfareedkhan.com)
    - Github: [Github](https://github.com/fareedkhands)
    - Kaggle: [Kaggle](https://www.kaggle.com/muhammadfareedkhan)
    - LinkedIn: [LinkedIn](https://www.linkedin.com/in/fareed-khan-385b79150/)
    - Twitter: [Twitter](https://twitter.com/fareedkhanmeyo)
