# **Creating Metrices:**
- 2D array is a matrix

In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2 (3 rows, 2 columns)
print(a)
print(a.shape) # (3, 2)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [11]:
# create a 2x3 matrix:
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 (2 rows, 3 columns)
print(b)
print(b.shape)   # (2, 3)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
# create a matrix of big dimensions:
c = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [21]:
# create a matrix
b = np.arange(0, 100, 2) # (start, stop, step) 
print(b) 
print('------------------')
print(b.ndim) # 1 dimension
# it's an array but not a matrix
# an array must be 2 dimensional for it to be a matrix
# to make it a matrix, use reshape

print(b.shape) # (50,) means 50 rows and 1 column

print('------------------')

print(b.reshape(5,10)) # reshape to 5 rows and 10 columns
print(b.reshape(5,10).ndim) # 2 dimensions = matrix

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
------------------
1
(50,)
------------------
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
2


#### **`Indexing` and `slicing` operations are useful when you’re manipulating matrices:**
**Indexing**: This is used to access a specific element in the matrix. 
- You provide an integer index for each dimension of the matrix to pinpoint the exact element you want. 
- For example: 
  - `matrix[1, 2]` would get the element at the second row and third column. 
  - Remember that Python uses 0-based indexing, so the first element is at index 0.

**Slicing**: 
- This is used to access a subset of the matrix. 
- Instead of providing a single integer for each dimension, you provide a range in the form `start:stop:step` to get multiple elements.
- For example: 
  - `matrix[1:3, 2:4]` would get a submatrix consisting of the second and third rows and the third and fourth columns.

Here's an example to illustrate the difference:

- Difference between indexing & slicing:

In [26]:
# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print(matrix[1, 2])  # 1 means 2nd row, 2 means 3rd column

# Slicing
print(matrix[1:3, 1:3]) # 1:3 means 2nd and 3rd row, 1:3 means 2nd and 3rd column


6
[[5 6]
 [8 9]]


In [24]:
#1 defining a matrix:
c = np.arange(0, 100, 2).reshape(5,10)
print(c)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [25]:
#2 slicing a matrix of 3 rows and 2 columns
print(c[1:3, 3:5]) # 1:3 means 2nd and 3rd row, 3:5 means 4th and 5th column

# c[:,:] means all rows and all columns

[[26 28]
 [46 48]]


#### **Key Points:**
- The code `print(c[1:3, 3:5])` is slicing `c`.

`1:3 is the slice for the rows`. 
  - It selects rows with index 1 and 2. 

`3:5 is the slice for the columns`. 
- It selects columns with index 3 and 4, which are the fourth and fifth columns of the matrix.

So, `c[1:3, 3:5]` creates a new 2D array that consists of the **`second and third rows`** and the **`fourth and fifth columns`** of `c`. 

> Note that the `stop value` in a slice is `exclusive`, so `1:3` includes indices 1 and 2, but not 3. Similarly, `3:5` includes indices 3 and 4, but not 5.

You can aggregate matrices the same way you aggregated vectors:

In [39]:
print(c.max())  # maximum
print(c.min())  # minimum
print(c.mean()) # average
print(c.sum())  # sum of all elements
print(c.std())  # standard deviation
print(c.var())  # variance

98
0
49.0
2450
28.861739379323623
833.0


In [33]:
c

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [45]:
print(c.max(axis=0)) # max(axis=0) means max value for each column
print('------------------')
print(c.max(axis=1)) # max(axis=1) means max value for each row

[80 82 84 86 88 90 92 94 96 98]
------------------
[18 38 58 78 98]


When `max` function used with the `axis` parameter, it finds the maximum values along a specified axis.

`c.max(axis=0)`: 
- This finds the maximum value in each column of the array `c`. 
- The `axis=0` parameter means that the operation is performed along the first dimension of the array (i.e., vertically). 
- If `c is a 2D array`, the result will be a 1D array with the same number of elements as the number of columns in `c`.

`c.max(axis=1)`: 
- This finds the maximum value in each row of the array `c`. 
- The `axis=1` parameter means that the operation is performed along the second dimension of the array (i.e., horizontally). 
- If `c is a 2D array`, the result will be a 1D array with the same number of elements as the number of rows in `c`.

In [46]:
d = np.arange(0,20,2).reshape(5,2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

Addition and Multiplication of matrices and arrays:

In [60]:
# Addition and Multiplication of matrices and arrays:
print(d + np.array([20, 22]))   # add 20 to 1st column, add 22 to 2nd column
print(d + 2) # adding 2 to all elements
print('------------------')
print(d * np.array([20, 22]))   # multiply 20 to 1st column, multiply 22 to 2nd column
print(d * 2) # multiply all elements by 2
print('------------------')
print(d / np.array([20, 22]))   # multiply 20 to 1st column, multiply 22 to 2nd column
print(d/2) # divide all elements by 2

[[20 24]
 [24 28]
 [28 32]
 [32 36]
 [36 40]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
------------------
[[  0  44]
 [ 80 132]
 [160 220]
 [240 308]
 [320 396]]
[[ 0  4]
 [ 8 12]
 [16 20]
 [24 28]
 [32 36]]
------------------
[[0.         0.09090909]
 [0.2        0.27272727]
 [0.4        0.45454545]
 [0.6        0.63636364]
 [0.8        0.81818182]]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


Adding a Row inside the original column:

In [56]:
# Adding Row at the bottom of the matrix:
np.vstack((d, np.array([42,44]))) # add a row [42,44] to the bottom of the matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [57]:
c

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [61]:
np.flip(c) # flip the matrix upside down

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])